### ISSUE TITLE
Feature: multi-select

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-range-list#3]
See ticket #9784

Adding support for checkboxes (in addition to radios) for multi-select.

**Comment by pablogiralt** [comment]
Added a pull request for this #4

**Comment by pablogiralt** [comment]
Hi @mgibbs189 have you taken a look at my pull request? I am using my versión in a new site I am developing an it is working without issues.  However I would be glad to work in more in the pull request if you have any comments

**Comment by mgibbs189** [comment]
@pablogiralt not yet unfortunately. I mentioned this PR to another customer who will likely give your changes a try!
